import type { CandidateAppDisplayLocale } from './candidate-locales.constant';

type CandidateLabels = Readonly<Record<CandidateAppDisplayLocale, string>>;

export const CANDIDATE_CATEGORY_LABELS: Readonly<Record<string, CandidateLabels>> = {
  animals: { en: 'Animals', tr: 'Hayvanlar', es: 'Animales', de: 'Tiere', fr: 'Animaux', 'pt-BR': 'Animais', it: 'Animali', ar: 'حيوانات', ja: '動物', ko: '동물', nl: 'Dieren', pl: 'Zwierzęta', ru: 'Животные', 'zh-Hans': '动物', 'zh-Hant': '動物', ca: 'Animals', cs: 'Zvířata', da: 'Dyr' , el: 'Ζώα' },
  'nature-flowers': { en: 'Nature & Flowers', tr: 'Doğa ve Çiçekler', es: 'Naturaleza y flores', de: 'Natur & Blumen', fr: 'Nature et fleurs', 'pt-BR': 'Natureza e Flores', it: 'Natura e Fiori', ar: 'الطبيعة والزهور', ja: '自然と花', ko: '자연과 꽃', nl: 'Natuur & Bloemen', pl: 'Natura i kwiaty', ru: 'Природа и цветы', 'zh-Hans': '自然与花卉', 'zh-Hant': '自然與花卉', ca: 'Natura i Flors', cs: 'Příroda a květiny', da: 'Natur & Blomster' , el: 'Φύση & Λουλούδια' },
  people: { en: 'People', tr: 'İnsanlar', es: 'Personas', de: 'Menschen', fr: 'Personnes', 'pt-BR': 'Pessoas', it: 'Persone', ar: 'الناس', ja: '人物', ko: '사람', nl: 'Mensen', pl: 'Ludzie', ru: 'Люди', 'zh-Hans': '人物', 'zh-Hant': '人物', ca: 'Persones', cs: 'Lidé', da: 'Mennesker' , el: 'Άνθρωποι' },
  'places-architecture': { en: 'Places & Architecture', tr: 'Yerler ve Mimari', es: 'Lugares y arquitectura', de: 'Orte & Architektur', fr: 'Lieux et architecture', 'pt-BR': 'Lugares e Arquitetura', it: 'Luoghi e Architettura', ar: 'الأماكن والعمارة', ja: '場所と建築', ko: '장소와 건축', nl: 'Plekken & Architectuur', pl: 'Miejsca i architektura', ru: 'Места и архитектура', 'zh-Hans': '地方与建筑', 'zh-Hant': '地方與建築', ca: 'Llocs i Arquitectura', cs: 'Místa a architektura', da: 'Steder & Arkitektur' , el: 'Τόποι & Αρχιτεκτονική' },
  'food-drink': { en: 'Food & Drink', tr: 'Yiyecek ve İçecek', es: 'Comida y bebida', de: 'Essen & Trinken', fr: 'Cuisine et boissons', 'pt-BR': 'Comidas e Bebidas', it: 'Cibo e Bevande', ar: 'طعام وشراب', ja: '食べ物と飲み物', ko: '음식과 음료', nl: 'Eten & Drinken', pl: 'Jedzenie i picie', ru: 'Еда и напитки', 'zh-Hans': '美食与饮品', 'zh-Hant': '美食與飲品', ca: 'Menjar i Beguda', cs: 'Jídlo a pití', da: 'Mad & Drikke' , el: 'Φαγητό & Ποτό' },
  'holidays-seasons': { en: 'Holidays & Seasons', tr: 'Tatiller ve Mevsimler', es: 'Festividades y estaciones', de: 'Feiertage & Jahreszeiten', fr: 'Fêtes et saisons', 'pt-BR': 'Datas Comemorativas e Estações', it: 'Festività e Stagioni', ar: 'العطلات والفصول', ja: '祝日と季節', ko: '기념일과 계절', nl: 'Feestdagen & Seizoenen', pl: 'Święta i pory roku', ru: 'Праздники и сезоны', 'zh-Hans': '节日与季节', 'zh-Hant': '節日與季節', ca: 'Festes i Estacions', cs: 'Svátky a roční období', da: 'Højtider & Årstider' , el: 'Γιορτές & Εποχές' },
  fantasy: { en: 'Fantasy', tr: 'Fantastik', es: 'Fantasía', de: 'Fantasy', fr: 'Fantaisie', 'pt-BR': 'Fantasia', it: 'Fantasy', ar: 'خيال', ja: 'ファンタジー', ko: '판타지', nl: 'Fantasie', pl: 'Fantasy', ru: 'Фэнтези', 'zh-Hans': '奇幻', 'zh-Hant': '奇幻', ca: 'Fantasia', cs: 'Fantasy', da: 'Fantasy' , el: 'Φαντασία' },
  'geometric-abstract': { en: 'Geometric & Abstract', tr: 'Geometrik ve Soyut', es: 'Geométrico y abstracto', de: 'Geometrisch & Abstrakt', fr: 'Géométrique et abstrait', 'pt-BR': 'Geométrico e Abstrato', it: 'Geometrico e Astratto', ar: 'هندسي وتجريدي', ja: '幾何学・抽象', ko: '기하학 및 추상', nl: 'Geometrisch & Abstract', pl: 'Geometryczne i abstrakcyjne', ru: 'Геометрия и абстракция', 'zh-Hans': '几何与抽象', 'zh-Hant': '幾何與抽象', ca: 'Geomètric i Abstracte', cs: 'Geometrické a abstraktní', da: 'Geometrisk & Abstrakt' , el: 'Γεωμετρικό & Αφηρημένο' },
  'words-symbols': { en: 'Words & Symbols', tr: 'Kelimeler ve Semboller', es: 'Palabras y símbolos', de: 'Worte & Symbole', fr: 'Mots et symboles', 'pt-BR': 'Palavras e Símbolos', it: 'Scritte e Simboli', ar: 'كلمات ورموز', ja: '言葉とシンボル', ko: '문구와 심볼', nl: 'Woorden & Symbolen', pl: 'Słowa i symbole', ru: 'Слова и символы', 'zh-Hans': '文字与符号', 'zh-Hant': '文字與符號', ca: 'Paraules i Símbols', cs: 'Slova a symboly', da: 'Ord & Symboler' , el: 'Λέξεις & Σύμβολα' },
  other: { en: 'Other', tr: 'Diğer', es: 'Otros', de: 'Sonstiges', fr: 'Autres', 'pt-BR': 'Outros', it: 'Altro', ar: 'أخرى', ja: 'その他', ko: '기타', nl: 'Overig', pl: 'Inne', ru: 'Другое', 'zh-Hans': '其他', 'zh-Hant': '其他', ca: 'Altres', cs: 'Ostatní', da: 'Andet' , el: 'Άλλο' },
};

export const CANDIDATE_TAG_LABELS: Readonly<Record<string, CandidateLabels>> = {
  retro: { en: 'Retro', tr: 'Retro', es: 'Retro', de: 'Retro', fr: 'Rétro', 'pt-BR': 'Retrô', it: 'Retrò', ar: 'ريترو', ja: 'レトロ', ko: '레트로', nl: 'Retro', pl: 'Retro', ru: 'Ретро', 'zh-Hans': '复古', 'zh-Hant': '復古', ca: 'Retro', cs: 'Retro', da: 'Retro' , el: 'Ρετρό' },
  dinosaur: { en: 'Dinosaur', tr: 'Dinozor', es: 'Dinosaurio', de: 'Dinosaurier', fr: 'Dinosaure', 'pt-BR': 'Dinossauro', it: 'Dinosauro', ar: 'ديناصور', ja: '恐竜', ko: '공룡', nl: 'Dinosaurus', pl: 'Dinozaur', ru: 'Динозавр', 'zh-Hans': '恐龙', 'zh-Hant': '恐龍', ca: 'Dinosaure', cs: 'Dinosaurus', da: 'Dinosaur' , el: 'Δεινόσαυρος' },
  kid: { en: 'Kids', tr: 'Çocuklar', es: 'Infantil', de: 'Kinder', fr: 'Enfants', 'pt-BR': 'Infantil', it: 'Bambini', ar: 'أطفال', ja: '子ども向け', ko: '어린이', nl: 'Kinderen', pl: 'Dzieci', ru: 'Дети', 'zh-Hans': '儿童', 'zh-Hant': '兒童', ca: 'Infantil', cs: 'Děti', da: 'Børn' , el: 'Παιδικό' },
  flower: { en: 'Flower', tr: 'Çiçek', es: 'Flor', de: 'Blume', fr: 'Fleur', 'pt-BR': 'Flor', it: 'Fiore', ar: 'زهرة', ja: '花', ko: '꽃', nl: 'Bloem', pl: 'Kwiat', ru: 'Цветок', 'zh-Hans': '花朵', 'zh-Hant': '花朵', ca: 'Flor', cs: 'Květina', da: 'Blomst' , el: 'Λουλούδι' },
  spring: { en: 'Spring', tr: 'İlkbahar', es: 'Primavera', de: 'Frühling', fr: 'Printemps', 'pt-BR': 'Primavera', it: 'Primavera', ar: 'ربيع', ja: '春', ko: '봄', nl: 'Lente', pl: 'Wiosna', ru: 'Весна', 'zh-Hans': '春天', 'zh-Hant': '春天', ca: 'Primavera', cs: 'Jaro', da: 'Forår' , el: 'Άνοιξη' },
  cute: { en: 'Cute', tr: 'Sevimli', es: 'Tierno', de: 'Niedlich', fr: 'Mignon', 'pt-BR': 'Fofo', it: 'Carino', ar: 'لطيف', ja: 'かわいい', ko: '귀여움', nl: 'Schattig', pl: 'Uroczy', ru: 'Милый', 'zh-Hans': '可爱', 'zh-Hant': '可愛', ca: 'Adorable', cs: 'Roztomilé', da: 'Sød' , el: 'Χαριτωμένο' },
  cat: { en: 'Cat', tr: 'Kedi', es: 'Gato', de: 'Katze', fr: 'Chat', 'pt-BR': 'Gato', it: 'Gatto', ar: 'قطة', ja: '猫', ko: '고양이', nl: 'Kat', pl: 'Kot', ru: 'Кот', 'zh-Hans': '猫', 'zh-Hant': '貓', ca: 'Gat', cs: 'Kočka', da: 'Kat' , el: 'Γάτα' },
  funny: { en: 'Funny', tr: 'Komik', es: 'Divertido', de: 'Lustig', fr: 'Drôle', 'pt-BR': 'Engraçado', it: 'Divertente', ar: 'مضحك', ja: 'ユーモラス', ko: '재미있음', nl: 'Grappig', pl: 'Zabawny', ru: 'Смешной', 'zh-Hans': '有趣', 'zh-Hant': '有趣', ca: 'Divertit', cs: 'Vtipné', da: 'Sjov' , el: 'Αστείο' },
  coffee: { en: 'Coffee', tr: 'Kahve', es: 'Café', de: 'Kaffee', fr: 'Café', 'pt-BR': 'Café', it: 'Caffè', ar: 'قهوة', ja: 'コーヒー', ko: '커피', nl: 'Koffie', pl: 'Kawa', ru: 'Кофе', 'zh-Hans': '咖啡', 'zh-Hant': '咖啡', ca: 'Cafè', cs: 'Káva', da: 'Kaffe' , el: 'Καφές' },
  warm: { en: 'Warm', tr: 'Sıcak', es: 'Cálido', de: 'Warm', fr: 'Chaleureux', 'pt-BR': 'Aconchegante', it: 'Caldo', ar: 'دافئ', ja: '暖かい', ko: '따뜻함', nl: 'Warm', pl: 'Ciepły', ru: 'Тёплый', 'zh-Hans': '温暖', 'zh-Hant': '溫暖', ca: 'Càlid', cs: 'Teplé', da: 'Varm' , el: 'Ζεστό' },
  cozy: { en: 'Cozy', tr: 'Rahat', es: 'Acogedor', de: 'Gemütlich', fr: 'Douillet', 'pt-BR': 'Aconchegante', it: 'Accogliente', ar: 'مريح', ja: '心地よい', ko: '아늑함', nl: 'Gezellig', pl: 'Przytulny', ru: 'Уютный', 'zh-Hans': '惬意', 'zh-Hant': '愜意', ca: 'Acollidor', cs: 'Útulné', da: 'Hyggelig' , el: 'Άνετο' },
  love: { en: 'Love', tr: 'Aşk', es: 'Amor', de: 'Liebe', fr: 'Amour', 'pt-BR': 'Amor', it: 'Amore', ar: 'حب', ja: '愛', ko: '사랑', nl: 'Liefde', pl: 'Miłość', ru: 'Любовь', 'zh-Hans': '爱', 'zh-Hant': '愛', ca: 'Amor', cs: 'Láska', da: 'Kærlighed' , el: 'Αγάπη' },
  heart: { en: 'Heart', tr: 'Kalp', es: 'Corazón', de: 'Herz', fr: 'Cœur', 'pt-BR': 'Coração', it: 'Cuore', ar: 'قلب', ja: 'ハート', ko: '하트', nl: 'Hart', pl: 'Serce', ru: 'Сердце', 'zh-Hans': '爱心', 'zh-Hant': '愛心', ca: 'Cor', cs: 'Srdce', da: 'Hjerte' , el: 'Καρδιά' },
  autumn: { en: 'Autumn', tr: 'Sonbahar', es: 'Otoño', de: 'Herbst', fr: 'Automne', 'pt-BR': 'Outono', it: 'Autunno', ar: 'خريف', ja: '秋', ko: '가을', nl: 'Herfst', pl: 'Jesień', ru: 'Осень', 'zh-Hans': '秋天', 'zh-Hant': '秋天', ca: 'Tardor', cs: 'Podzim', da: 'Efterår' , el: 'Φθινόπωρο' },
  leaf: { en: 'Leaf', tr: 'Yaprak', es: 'Hoja', de: 'Blatt', fr: 'Feuille', 'pt-BR': 'Folha', it: 'Foglia', ar: 'ورقة شجر', ja: '葉', ko: '잎', nl: 'Blad', pl: 'Liść', ru: 'Лист', 'zh-Hans': '叶子', 'zh-Hant': '葉子', ca: 'Fulla', cs: 'List', da: 'Blad' , el: 'Φύλλο' },
  orange: { en: 'Orange', tr: 'Turuncu', es: 'Naranja', de: 'Orange', fr: 'Orange', 'pt-BR': 'Laranja', it: 'Arancione', ar: 'برتقالي', ja: 'オレンジ', ko: '주황색', nl: 'Oranje', pl: 'Pomarańczowy', ru: 'Оранжевый', 'zh-Hans': '橙色', 'zh-Hant': '橙色', ca: 'Taronja', cs: 'Oranžová', da: 'Orange' , el: 'Πορτοκαλί' },
  star: { en: 'Star', tr: 'Yıldız', es: 'Estrella', de: 'Stern', fr: 'Étoile', 'pt-BR': 'Estrela', it: 'Stella', ar: 'نجمة', ja: '星', ko: '별', nl: 'Ster', pl: 'Gwiazda', ru: 'Звезда', 'zh-Hans': '星星', 'zh-Hant': '星星', ca: 'Estrella', cs: 'Hvězda', da: 'Stjerne' , el: 'Αστέρι' },
  magic: { en: 'Magic', tr: 'Sihir', es: 'Magia', de: 'Magie', fr: 'Magie', 'pt-BR': 'Magia', it: 'Magia', ar: 'سحر', ja: '魔法', ko: '마법', nl: 'Magie', pl: 'Magia', ru: 'Магия', 'zh-Hans': '魔法', 'zh-Hant': '魔法', ca: 'Màgia', cs: 'Kouzlo', da: 'Magi' , el: 'Μαγεία' },
  purple: { en: 'Purple', tr: 'Mor', es: 'Morado', de: 'Lila', fr: 'Violet', 'pt-BR': 'Roxo', it: 'Viola', ar: 'بنفسجي', ja: '紫', ko: '보라색', nl: 'Paars', pl: 'Fioletowy', ru: 'Фиолетовый', 'zh-Hans': '紫色', 'zh-Hant': '紫色', ca: 'Lila', cs: 'Fialová', da: 'Lilla' , el: 'Μοβ' },
  pattern: { en: 'Pattern', tr: 'Desen', es: 'Patrón', de: 'Muster', fr: 'Motif', 'pt-BR': 'Padrão', it: 'Motivo', ar: 'نمط', ja: '模様', ko: '패턴', nl: 'Patroon', pl: 'Wzór', ru: 'Узор', 'zh-Hans': '图案', 'zh-Hant': '圖案', ca: 'Patró', cs: 'Vzor', da: 'Mønster' , el: 'Μοτίβο' },
  peace: { en: 'Peace', tr: 'Barış', es: 'Paz', de: 'Frieden', fr: 'Paix', 'pt-BR': 'Paz', it: 'Pace', ar: 'سلام', ja: '平和', ko: '평화', nl: 'Vrede', pl: 'Pokój', ru: 'Мир', 'zh-Hans': '和平', 'zh-Hant': '和平', ca: 'Pau', cs: 'Mír', da: 'Fred' , el: 'Ειρήνη' },
  symbol: { en: 'Symbol', tr: 'Sembol', es: 'Símbolo', de: 'Symbol', fr: 'Symbole', 'pt-BR': 'Símbolo', it: 'Simbolo', ar: 'رمز', ja: 'シンボル', ko: '심볼', nl: 'Symbool', pl: 'Symbol', ru: 'Символ', 'zh-Hans': '符号', 'zh-Hant': '符號', ca: 'Símbol', cs: 'Symbol', da: 'Symbol' , el: 'Σύμβολο' },
  desert: { en: 'Desert', tr: 'Çöl', es: 'Desierto', de: 'Wüste', fr: 'Désert', 'pt-BR': 'Deserto', it: 'Deserto', ar: 'صحراء', ja: '砂漠', ko: '사막', nl: 'Woestijn', pl: 'Pustynia', ru: 'Пустыня', 'zh-Hans': '沙漠', 'zh-Hant': '沙漠', ca: 'Desert', cs: 'Poušť', da: 'Ørken' , el: 'Έρημος' },
  plant: { en: 'Plant', tr: 'Bitki', es: 'Planta', de: 'Pflanze', fr: 'Plante', 'pt-BR': 'Planta', it: 'Pianta', ar: 'نبات', ja: '植物', ko: '식물', nl: 'Plant', pl: 'Roślina', ru: 'Растение', 'zh-Hans': '植物', 'zh-Hant': '植物', ca: 'Planta', cs: 'Rostlina', da: 'Plante' , el: 'Φυτό' },
  food: { en: 'Food', tr: 'Yiyecek', es: 'Comida', de: 'Essen', fr: 'Cuisine', 'pt-BR': 'Comida', it: 'Cibo', ar: 'طعام', ja: '食べ物', ko: '음식', nl: 'Eten', pl: 'Jedzenie', ru: 'Еда', 'zh-Hans': '美食', 'zh-Hant': '美食', ca: 'Menjar', cs: 'Jídlo', da: 'Mad' , el: 'Φαγητό' },
  pizza: { en: 'Pizza', tr: 'Pizza', es: 'Pizza', de: 'Pizza', fr: 'Pizza', 'pt-BR': 'Pizza', it: 'Pizza', ar: 'بيتزا', ja: 'ピザ', ko: '피자', nl: 'Pizza', pl: 'Pizza', ru: 'Пицца', 'zh-Hans': '披萨', 'zh-Hant': '披薩', ca: 'Pizza', cs: 'Pizza', da: 'Pizza' , el: 'Πίτσα' },
  yummy: { en: 'Yummy', tr: 'Lezzetli', es: 'Delicioso', de: 'Lecker', fr: 'Délicieux', 'pt-BR': 'Delicioso', it: 'Delizioso', ar: 'لذيذ', ja: 'おいしい', ko: '맛있음', nl: 'Lekker', pl: 'Pyszne', ru: 'Вкусно', 'zh-Hans': '美味', 'zh-Hant': '美味', ca: 'Deliciós', cs: 'Lahodné', da: 'Lækker' , el: 'Νόστιμο' },
  castle: { en: 'Castle', tr: 'Kale', es: 'Castillo', de: 'Schloss', fr: 'Château', 'pt-BR': 'Castelo', it: 'Castello', ar: 'قلعة', ja: '城', ko: '성', nl: 'Kasteel', pl: 'Zamek', ru: 'Замок', 'zh-Hans': '城堡', 'zh-Hant': '城堡', ca: 'Castell', cs: 'Hrad', da: 'Slot' , el: 'Κάστρο' },
  stone: { en: 'Stone', tr: 'Taş', es: 'Piedra', de: 'Stein', fr: 'Pierre', 'pt-BR': 'Pedra', it: 'Pietra', ar: 'حجر', ja: '石', ko: '돌', nl: 'Steen', pl: 'Kamień', ru: 'Камень', 'zh-Hans': '石头', 'zh-Hant': '石頭', ca: 'Pedra', cs: 'Kámen', da: 'Sten' , el: 'Πέτρα' },
};

export const CANDIDATE_TAXONOMY_COVERAGE = Object.fromEntries(
  (['en', 'tr', 'es', 'de', 'fr', 'pt-BR', 'it', 'ar', 'ja', 'ko', 'nl', 'pl', 'ru', 'zh-Hans', 'zh-Hant', 'ca', 'cs', 'da', 'el'] as const).map((locale) => [locale, {
    categories: Object.values(CANDIDATE_CATEGORY_LABELS).filter((labels) => labels[locale]).length,
    tags: Object.values(CANDIDATE_TAG_LABELS).filter((labels) => labels[locale]).length,
  }]),
);
